// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtOk8E8piAd27bJPVVQEe_KG8xJ_crONI',
    appId: '1:672579198545:web:ca67ddf2b1f9c9e1d16270',
    messagingSenderId: '672579198545',
    projectId: 'greenlink-1b0c1',
    authDomain: 'greenlink-1b0c1.firebaseapp.com',
    storageBucket: 'greenlink-1b0c1.appspot.com',
    measurementId: 'G-BG6YZHGWWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCg4mP_OupzC3unN9jTwA4dIfjUX2RnsY',
    appId: '1:672579198545:android:5e352f3ea9d5e8d0d16270',
    messagingSenderId: '672579198545',
    projectId: 'greenlink-1b0c1',
    storageBucket: 'greenlink-1b0c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhrdUiEs1AVp8LDVGw6xWkrkgpxozIcv0',
    appId: '1:672579198545:ios:1bb7dad4efa35c48d16270',
    messagingSenderId: '672579198545',
    projectId: 'greenlink-1b0c1',
    storageBucket: 'greenlink-1b0c1.appspot.com',
    iosClientId: '672579198545-qdved4csttbt8kla8m5sgg15mdt54bo4.apps.googleusercontent.com',
    iosBundleId: 'com.example.solarWeb',
  );
}
